/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrayCondition: typeof import('./src/components/ArrayCondition.vue')['default']
    ArrayItem: typeof import('./src/components/ArrayItem.vue')['default']
    Draggable: typeof import('./src/components/Draggable.vue')['default']
    GetArrayOne: typeof import('./src/components/GetArrayOne.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    QrCode: typeof import('./src/components/QrCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopover: typeof import('vant/es')['Popover']
  }
}
